### ISSUE TITLE
Uninstall Now.app documentation/option/app

### ISSUE THREAD

**Issue by backspaces** [zeit/now-desktop#219]
Now.app should be easily uninstalled if you are happy with the npm now-cli and no longer need the GUI. Please add docs or Now.app option or an app to uninstall Now.app.

Here's what I see as dependencies via AppZapper. My guess is that the cache needn't be deleted
![snap 12 16 16-13 31 02](https://cloud.githubusercontent.com/assets/124366/21280534/c1de9e4e-c3a3-11e6-9a98-2997c266b230.jpg)

**Comment by leo** [comment]
I don't think this is a good idea. The common workflow for removing applications on macOS is simply removing them from the "Applications" directory (that's what most of our users do). I also don't think that someone should care about these cache files. It will simply make starting over easier if you decide to install the app again in the future...

**Comment by RedaBenh** [comment]
I don't think that 'now' application can be removed easily just by deleting it from "Application" folder.
I uninstall it 3 weeks ago and now i get the notification bellow
![image](https://cloud.githubusercontent.com/assets/1609466/25950398/262974da-365b-11e7-9e2e-375e70e04979.png)

Do you have some uninstall script? a document that list all files to delete ?

Thanks

**Comment by jonathanwmaddison** [comment]
I have the same problem as RedaBenh, above. It makes Now feel like spam :(

**Comment by lodalo** [comment]
I am trying to remove now.app since it crashes when I try to open it. I can't see docs related to the complete removal. :-(

I have a ton of files in the folder:
/private/var/folders/94/706dbty57cd5nskwyvx7l3dr0000xp/T

Which look like:
co.zeit.now.ShipIt.zyCaY5XT
co.zeit.now.ShipIt.zAp0ezms
etc.....

(I found the files doing a scan to determine what is taking so much space in my drive.)
