### ISSUE TITLE
Repeated notifications of having updated CLI

### ISSUE THREAD

**Issue by lunelson** [zeit/now-desktop#280]
The app is either continually re-updating the CLI (always the same version), or at least continuing to notify me about it. I guess it is not recognizing that the update has already happened or the notification has already been made...?

![image](https://cloud.githubusercontent.com/assets/1242864/24446083/83796d68-146c-11e7-9a50-161720a3f809.png)

**Comment by leo** [comment]
Should be fixed by https://github.com/zeit/now-desktop/commit/92a50aa35d9d81bdddf9e3266f206a3bed48d8f5

**Comment by wishinghand** [comment]
I'm getting this issue on the latest release. I installed on April 10th or 11th.

**Comment by leo** [comment]
How often are you getting the notifications?

**Comment by wishinghand** [comment]
About 3-4 times an hour.

**Comment by wishinghand** [comment]
![image](https://cloud.githubusercontent.com/assets/4001750/24977935/be6ae588-1f83-11e7-819b-082765fefa0c.png)

**Comment by wishinghand** [comment]
It might be every 10 minutes. I noticed it happened at 1:29pm and just now at 1:39pm. Will report back at 1:49pm.

**Comment by wishinghand** [comment]
Yup, it's every 10 minutes.

**Comment by leo** [comment]
Could it be possible that you have the npm binary installed as well? Can you show me the output of this command, please:

```
npm list -g --depth=0
```

**Comment by wishinghand** [comment]
I have this version of Now installed from that output:
now@4.10.3

**Comment by leo** [comment]
I see! That's the problem. There's a difference between the npm binary and the one from the app (that one actually contains node, so that it works on devices even without node). So I suggest uninstalling all instances of the binary and then using the app to install the binary again (you can do that by clicking on "Tutorial" in the "About" window).

After that, restart the application and it should work just fine. From there one, you should never install the npm binary again, otherwise you'll have to different instances of the CLI again (which will cause problems with Now Desktop).
