### ISSUE TITLE
permission denied: now

### ISSUE THREAD

**Issue by lukechilds** [zeit/now-desktop#305]
I often get popups asking for me to enter my password when now is updating in the background. The last time it did this I was in the middle of something else so I cancelled the popup. Now I'm trying to do a deploy and I'm just getting `permission denied: now` on the cli.

I can't see a way to re-init the download from the desktop app so I can enter my password. Is this expected, are you supposed to have to enter your password each time?

**Comment by lukechilds** [comment]
Ok, so I did a bit more digging, `which now` was returning `now not found`. I had a read through `main/utils/binary.js` and checked the dirs in there. I found `now` in `/usr/local/bin`, however it wasn't set as executable:

```shell
$ ls -lah '/usr/local/bin/now'
-rw-r--r--  1 lukechilds  staff    42M 17 May 11:34 /usr/local/bin/now

$ /usr/local/bin/now
zsh: permission denied: /usr/local/bin/now
```

`chmod +x /usr/local/bin/now` fixed the problem and now I can use `now` as normal.

So it seems (for me at least), now-desktop can update `now` in `/usr/local/bin` but can't set it as executable without requesting a password prompt from the user.

I'm on MacOS and just installed via the desktop download app. I did already have now installed via npm (since uninstalled) when I installed now-desktop if that could of effected anything?

**Comment by shockwavemoto** [comment]
Ok, so I did a bit more digging, which now was returning now not found. I had a read through main/utils/binary.js and checked the dirs in there. I found now in /usr/local/bin, however it wasn't set as executable:
$ ls -lah '/usr/local/bin/now'
-rw-r--r--  1 lukechilds  staff    42M 17 May 11:34 /usr/local/bin/now
$ /usr/local/bin/now
zsh: permission denied: /usr/local/bin/now
chmod +x /usr/local/bin/now fixed the problem and now I can use now as normal.
So it seems (for me at least), now-desktop can update now in /usr/local/bin but can't set it as executable without requesting a password prompt from the user.
I'm on MacOS and just installed via the desktop download app. I did already have now installed via npm (since uninstalled) when I installed now-desktop if that could of effected anything?

chmod seems reasonable choice to do this I don't think that it would affect anything, npm and your brew is different so i don't think that was the problem. I guess it was only of permissions problem

**Comment by lukechilds** [comment]
I still get a password prompt every single time now updates in the background

**Comment by leo** [comment]
@lukechilds We're releasing a big update soon, which should fix this! 🙏

**Comment by lukechilds** [comment]
@leo Did you just push that update? I just got a warning window popup that seems related:


> **/bin/sh: ./sudo-prompt-script: No such file or directory**
> /bin/sh: ./sudo-prompt-script: No such file or directory (127)

**Comment by leo** [comment]
No, we didn't. Let's find out if the coming release fixes this! 😊

**Comment by leo** [comment]
An update is coming very soon. If it doesn't fix the issue, please let us know!

**Comment by lukechilds** [comment]
Great, thanks!
