### ISSUE TITLE
Weird behaviour when clicking the menubar icon

### ISSUE THREAD

**Issue by vebjorni** [zeit/now-desktop#368]
Hi.

Don't know if this is already adressed or intended, but when I have multiple desktops on my Mac and clicking on the triangle menubar icon, it switches to a specific window before opening. See the behaveiour below.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9068991/30479088-f3f1c130-9a13-11e7-95e7-8167da20afb1.gif)

**Comment by PerStirpes** [comment]
This can be fixed by dragging the app into the dock > right click > options > assign to All Desktops > then remove from the dock. Once the flag is triggered the change will persist, until it's changed again by the user. I didn't see a way in the electron docs to access desktop window assignment. Now desktop does a brilliant job of mocking a menubar app but it's just like any other desktop app in that it respects the window that you initially opened the app in. I hope that helps. 

![kapture 2017-09-30 at 18 17 27](https://user-images.githubusercontent.com/19398470/31050822-bb1d54ba-a60b-11e7-9257-3cdd238b4445.gif)

**Comment by leo** [comment]
Thank you for clarifying how to fix this! 🙏
